---
apiVersion: v1
kind: Secret
metadata:
  name: apicast-config
type: Opaque
stringData:
  config.json: |
    {
      "services": [
        {
          "backend_version": "1",
          "proxy": {
              "hosts": ["one"],
              "api_backend": "http://httpbin.org",
              "backend": {
                  "endpoint": "http://127.0.0.1:8081",
                  "host": "backend"
              },
              "proxy_rules": [
                  {
                      "http_method": "GET",
                      "pattern": "/",
                      "metric_system_name": "hits",
                      "delta": 1,
                      "parameters": [],
                      "querystring_parameters": {}
                  }
              ]
          }
        }
      ]
    }
