apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager-v2
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
#        com.company: Red_Hat
#        rht.prod_name: Red_Hat_Integration
#        rht.prod_ver: master
#        rht.comp: 3scale_apicast
#        rht.comp_ver: 2.15
#        rht.subcomp: apicast_operator
#        rht.subcomp_t: infrastructure
    spec:
      serviceAccountName: apicast-operator
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RELATED_IMAGE_APICAST
          value: "quay.io/3scale/apicast:v3.15.0"
      terminationGracePeriodSeconds: 10
