version: 2.1

orbs:
  go: circleci/go@1.7.1

commands:
  attach-workspace:
    steps:
    - run:
        name: Preparing workspace directory
        command: |
          sudo rm -rf /tmp/workspace
          sudo mkdir -p /tmp/workspace
          sudo chown -vf circleci:circleci /tmp/workspace
        working_directory: /
    - attach_workspace:
        at: /tmp/workspace

  docker-login:
    steps:
      - run:
          name: Docker login
          command: |
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" "${DOCKER_REGISTRY}"

  build-operator-image:
    steps:
      - checkout
      - run:
          name: Build Operator
          command: |
              make docker-build-only IMG=apicast-operator:latest

jobs:
  install-operator:
    docker:
      - image: quay.io/3scale/operators-ci-images:v1.20
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - build-operator-image
      - run:
          name: Sharing requirements to downstream job
          command: |
            mkdir -p /tmp/workspace/images
            docker save -o /tmp/workspace/images/operator-image.tar apicast-operator:latest
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - images/operator-image.tar

  license-check:
    docker:
      - image: quay.io/3scale/operators-ci-images:v1.20
    steps:
      - run:
          name: Installing ruby
          command: |
            # Determine if sudo is neccessary
            SUDO=""
            if [[ $EUID -ne 0 ]]; then
            SUDO=sudo
            fi
            # Install ruby
            $SUDO apt-get update --allow-releaseinfo-change && $SUDO apt-get install -y ruby-full
      - run:
          name: Installing License tool
          command: |
            # Determine if sudo is neccessary
            SUDO=""
            if [[ $EUID -ne 0 ]]; then
            SUDO=sudo
            fi
            # Install ruby
            $SUDO gem install license_finder --version 5.7.1
      - checkout
      - run: make download
      - run: make licenses-check

  tag-operator-image-master:
    machine:
      image: ubuntu-2404:current
      docker_layer_caching: true
    steps:
      - attach-workspace
      - run:
          name: Unpack docker image
          command: |
            docker load -i /tmp/workspace/images/operator-image.tar
      - run:
          name: Tag image as master
          command: |
              docker tag apicast-operator:latest quay.io/3scale/apicast-operator:master
      - docker-login
      - run:
          name: Push master image
          command: |
              docker push quay.io/3scale/apicast-operator:master
      - run:
          name: Tag image as latest
          command: |
            docker tag quay.io/3scale/apicast-operator:master quay.io/3scale/apicast-operator:latest
      - run:
          name: Push latest image
          command: |
              docker push quay.io/3scale/apicast-operator:latest

  tag-operator-image-release:
    machine:
      image: ubuntu-2404:current
      docker_layer_caching: true
    steps:
      - attach-workspace
      - run:
          name: Unpack docker image
          command: |
            docker load -i /tmp/workspace/images/operator-image.tar
      - run:
          name: Tag image as release ${CIRCLE_TAG}
          command: |
              docker tag apicast-operator:latest quay.io/3scale/apicast-operator:${CIRCLE_TAG}
      - docker-login
      - run:
          name: Push ${CIRCLE_TAG} tag
          command: |
              docker push quay.io/3scale/apicast-operator:${CIRCLE_TAG}

  run-unit-test:
    docker:
      - image: quay.io/3scale/operators-ci-images:v1.20
    steps:
      - checkout
      - run:
          name: run unit tests
          command: |
            make test-unit

  run-integration-test:
    machine:
      image: ubuntu-2404:current
      docker_layer_caching: true
    steps:
      - go/install:
          version: '1.20.14'
      - checkout
      - run:
          name: Install KinD
          command: |
            make kind
      - run:
          name: Create Kubernetes Cluster
          command: |
            make kind-create-cluster
      - run:
          name: run integration tests
          command: |
            make test-integration
          no_output_timeout: 30m

  lint:
    docker:
      - image: quay.io/3scale/operators-ci-images:v1.20
    steps:
      - checkout
      - run:
          name: Go Lint
          command: |
            make run-lint

  bundle-validate:
    docker:
      - image: quay.io/3scale/operators-ci-images:v1.20
    steps:
      - checkout
      - run: make bundle
      - run: make bundle-update-test

workflows:
  version: 2
  build:
    jobs:
      - license-check
      - bundle-validate
      - lint
      - run-unit-test
      - run-integration-test
      - install-operator:
          filters: # required since `tag-operator-image-release` job has tag filters AND requires `install-operator`. Otherwise tag build will not be triggered on new tags
            tags:
              only: /^v.*/
      - tag-operator-image-master:
          context: org-global
          requires:
            - run-unit-test
            - run-integration-test
            - install-operator
          filters:
            branches:
              only: master
      - tag-operator-image-release:
          context: org-global
          requires:
            - run-unit-test
            - run-integration-test
            - install-operator
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
