version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.7.0

commands:
  start-minikube:
    steps:
    - run:
        command: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
            && chmod +x minikube
          sudo cp minikube /usr/local/bin && rm minikube
          sudo -E minikube start --vm-driver=none --cpus 2 --memory 2048
        name: Start minikube

  attach-workspace:
    steps:
    - run:
        name: Preparing workspace directory
        command: |
          sudo rm -rf /tmp/workspace
          sudo mkdir -p /tmp/workspace
          sudo chown -vf circleci:circleci /tmp/workspace
        working_directory: /
    - attach_workspace:
        at: /tmp/workspace

  docker-login:
    steps:
      - run:
          name: Docker login
          command: |
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" "${DOCKER_REGISTRY}"

  install-golang:
    steps:
      - run:
          name: Setup GO env
          command: |
            mkdir -p ~/tmp
            echo 'export TMPDIR=~/tmp/' >> $BASH_ENV
            echo 'export GOROOT=/opt/go' >> $BASH_ENV
            echo 'export GOPATH=~/go' >> $BASH_ENV
            sudo mkdir -p /opt/go/bin
            mkdir -p ~/go/bin
            echo 'export PATH=$GOROOT/bin:$PATH' >> $BASH_ENV
            echo 'export PATH=$GOPATH/bin:$PATH' >> $BASH_ENV
      - run:
          name: Install Golang
          command: |
            curl --fail -L https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz | sudo tar -C /opt -xzf-

  install-operator-sdk:
    steps:
      - run:
          name: Install operator-sdk
          command: |
            export OPERATOR_SDK_RELEASE_VERSION=v0.8.0
            curl -OJL https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_RELEASE_VERSION}/operator-sdk-${OPERATOR_SDK_RELEASE_VERSION}-x86_64-linux-gnu
            chmod +x operator-sdk-${OPERATOR_SDK_RELEASE_VERSION}-x86_64-linux-gnu && sudo cp operator-sdk-${OPERATOR_SDK_RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${OPERATOR_SDK_RELEASE_VERSION}-x86_64-linux-gnu

  install-openshift:
    steps:
      - run:
          name: Install OpenShift Client Tools
          working_directory: /tmp
          command: |
            curl --fail -L  https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz | tar -xzf-
            sudo mv /tmp/openshift-origin-client-tools-*-linux-64bit/oc /usr/local/bin/
            sudo mv /tmp/openshift-origin-client-tools-*-linux-64bit/kubectl /usr/local/bin/
      - run:
          name: Configure Docker
          command: |
            echo '{"insecure-registries": ["172.30.0.0/16"]}' | sudo tee --append /etc/docker/daemon.json
            sudo service docker restart

      - run:
          name: Get docker host IP
          command: |
            echo "export DOCKER_HOST_IP=$(docker run --net=host codenvy/che-ip)" >> $BASH_ENV

      - run:
          name: Start and Configure OpenShift Cluster
          working_directory: /tmp/openshift
          command: |
            oc cluster up --public-hostname=${DOCKER_HOST_IP} --enable=persistent-volumes \
              --enable=registry --enable=router
            oc login https://${DOCKER_HOST_IP}:8443 -u system:admin --insecure-skip-tls-verify=true > /dev/null
            oc adm policy add-cluster-role-to-user cluster-admin developer > /dev/null
            oc adm policy add-scc-to-group hostmount-anyuid system:serviceaccounts
            oc login https://${DOCKER_HOST_IP}:8443 -u developer --insecure-skip-tls-verify=true > /dev/null

            oc wait --timeout=90s --for=condition=available dc/docker-registry --namespace=default || oc rollout retry dc/docker-registry --namespace=default

  oc-observe:
    steps:
      - run:
          name: Observe OpenShift Pod changes
          command: |
            oc observe pods --maximum-errors=-1 --no-headers --object-env-var=OBJECT --type-env-var=TYPE -- jq -n --raw-output 'env.OBJECT | fromjson | "\(env.TYPE) \(.kind) \(.metadata.name) started at \(.status.startTime) (\(.status.phase)) \(.status.conditions // [] | map("\(.type): \(.status) @ \(.lastTransitionTime)") | join(", "))"'
          background: true

  watch-operator-pod:
    steps:
      - run:
          name: Watch pod resource
          command: |
            OPERATOR_POD=$(kubectl get pods -l name=apicast-operator -n operator-test -o 'jsonpath={..metadata.name}')
            while [[ -z "${OPERATOR_POD}" ]]; do
              echo "waiting for pod" && sleep 1;
              OPERATOR_POD=$(kubectl get pods -l name=apicast-operator -n operator-test -o 'jsonpath={..metadata.name}')
            done
            while true; do kubectl describe pods ${OPERATOR_POD} -n operator-test; sleep 5; done

          background: true

  watch-operator-pod-logs:
    steps:
      - run:
          name: Watch pod logs
          command: |
            while [[ $(kubectl get pods -l name=apicast-operator -n operator-test -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do
              echo "waiting for pod" && sleep 1
            done
            OPERATOR_POD=$(kubectl get pods -l name=apicast-operator -n operator-test -o 'jsonpath={..metadata.name}')
            echo "watching logs on $OPERATOR_POD"
            kubectl -n operator-test logs -f $OPERATOR_POD

          background: true

  k8s-show-events:
    steps:
      - run:
          name: Collect k8s events
          command: |
            kubectl get events -n operator-test
          when: always

  oc-status:
    parameters:
      report_name:
        type: string
        default: "events"
    steps:
      - run:
          name: Collect OpenShift events and status
          command: |
            mkdir -p reports
            oc status
            oc get events -o json > reports/<< parameters.report_name >>.json
          when: always
      - store_artifacts:
          path: reports

  install-operator-dependencies:
    steps:
      - restore_cache:
          keys:
            - v3-apicastoperator-vendor-{{ arch }}-{{ checksum "go.sum" }}
            - v3-apicastoperator-vendor-{{ arch }}
      - run:
          name: Install operator dependencies
          command: |
            make vendor
      - save_cache:
          key: v3-apicastoperator-vendor-{{ arch }}-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg"

  build-operator-image:
    steps:
      - checkout
      - install-operator-sdk
      - install-operator-dependencies
      - run:
          name: Build Operator
          command: |
              make build IMAGE=172.30.1.1:5000/openshift/apicast-operator VERSION=test

jobs:
  install-operator:
    docker:
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/3scale/apicast-operator
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - build-operator-image
      - run:
          name: Sharing requirements to downstream job
          command: |
            mkdir -p /tmp/workspace/images
            docker save -o /tmp/workspace/images/operator-image.tar 172.30.1.1:5000/openshift/apicast-operator:test
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - images/operator-image.tar

  license-check:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - install-golang
      - checkout
      - run: sudo gem install license_finder --version 5.7.1
      - run: make licenses-check

  tag-operator-image-master:
    machine:
      image: circleci/classic:latest
      docker_layer_caching: true
    steps:
      - attach-workspace
      - run:
          name: Unpack docker image
          command: |
            docker load -i /tmp/workspace/images/operator-image.tar
      - run:
          name: Tag image as master
          command: |
              docker tag 172.30.1.1:5000/openshift/apicast-operator:test quay.io/3scale/apicast-operator:master
      - docker-login
      - run:
          name: Push master image
          command: |
              docker push quay.io/3scale/apicast-operator:master
      - run:
          name: Tag image as latest
          command: |
            docker tag quay.io/3scale/apicast-operator:master quay.io/3scale/apicast-operator:latest
      - run:
          name: Push latest image
          command: |
              docker push quay.io/3scale/apicast-operator:latest

  tag-operator-image-release:
    machine:
      image: circleci/classic:latest
      docker_layer_caching: true
    steps:
      - attach-workspace
      - run:
          name: Unpack docker image
          command: |
            docker load -i /tmp/workspace/images/operator-image.tar
      - run:
          name: Tag image as release ${CIRCLE_TAG}
          command: |
              docker tag 172.30.1.1:5000/openshift/apicast-operator:test quay.io/3scale/apicast-operator:${CIRCLE_TAG}
      - docker-login
      - run:
          name: Push ${CIRCLE_TAG} tag
          command: |
              docker push quay.io/3scale/apicast-operator:${CIRCLE_TAG}
  run-k8s-e2e-test:
    environment: CHANGE_MINIKUBE_NONE_USER=true
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - kubernetes/install-kubectl
      - start-minikube
      - install-golang
      - install-operator-sdk
      - checkout
      - install-operator-dependencies
      - attach-workspace
      - run:
          name: Unpack and use local images by re-using the Docker daemon
          command: |
            docker load -i /tmp/workspace/images/operator-image.tar
      - kubernetes/create-or-update-resource:
          resource-file-path: test/resources/namespace-operator-test.yaml
          show-kubectl-command: true
      - watch-operator-pod
      - watch-operator-pod-logs
      - run:
          name: run E2E tests
          command: |
            make e2e-run IMAGE=172.30.1.1:5000/openshift/apicast-operator:${CIRCLE_SHA1} NAMESPACE=operator-test
          no_output_timeout: 30m
      - k8s-show-events

  run-openshift-e2e-test:
    machine:
      image: circleci/classic:latest
      docker_layer_caching: true
    resource_class: large
    working_directory: ~/go/src/github.com/3scale/apicast-operator
    steps:
      - install-openshift
      - install-golang
      - install-operator-sdk
      - checkout
      - install-operator-dependencies
      - attach-workspace
      - run:
          name: Unpack and push operator to internal registry
          command: |
            docker load -i /tmp/workspace/images/operator-image.tar
            oc whoami -t | docker login --username developer --password-stdin 172.30.1.1:5000
            docker push 172.30.1.1:5000/openshift/apicast-operator:test
      - run:
          name: Change to new testing namespace
          command: |
            oc new-project operator-test
      - oc-observe
      - run:
          name: run E2E tests
          command: |
            make e2e-run IMAGE=172.30.1.1:5000/openshift/apicast-operator:test NAMESPACE=operator-test
          no_output_timeout: 30m
      - oc-status

  test-crds:
    docker:
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/3scale/apicast-operator
    steps:
      - checkout
      - run: make test-crds

  verify-manifest:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip3 install operator-courier
      - run: make verify-manifest

workflows:
  version: 2
  build:
    jobs:
      - license-check
      - verify-manifest
      - test-crds
      - install-operator
      - run-openshift-e2e-test:
          requires:
            - install-operator
      - run-k8s-e2e-test:
          requires:
            - install-operator
      - tag-operator-image-master:
          context: org-global
          requires:
            - install-operator
          filters:
            branches:
              only: master
      - tag-operator-image-release:
          context: org-global
          requires:
            - install-operator
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
