apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.1.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: apicast-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: APIcast is the Schema for the apicasts API
      displayName: APIcast
      kind: APIcast
      name: apicasts.apps.3scale.net
      version: v1alpha1
  description: APIcast is an API gateway built on top of NGINX. It is part of the Red Hat 3scale API Management Platform
  displayName: APIcast (nightly)
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - 3scale
  - API
  - api
  - apicast
  - gateway
  - api-gateway
  - openresty
  links:
  - name: Apicast Operator
    url: https://apicast-operator.domain
  maintainers:
  - email: msoriano+apicastoperator@redhat.com
    name: Miguel Soriano
  - email: eastizle+apicastoperator@redhat.com
    name: Eguzki Astiz
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
