apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicast-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apicast-operator
  template:
    metadata:
      labels:
        name: apicast-operator
    spec:
      serviceAccountName: apicast-operator
      containers:
        - name: apicast-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - apicast-operator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "apicast-operator"
