# The following patch adds the 'app' label for the APIcast CRD
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apicasts.apps.3scale.net
  labels:
    app: apicast
