# The following patch adds `anyOf` OpenAPI
# validation for the configuration source of APIcast
# to the APIcast CRD due to at the moment
# of writing this (2020-06-22) kubebuilder
# does not support `anyOf` statement OpenAPI validation
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apicasts.apps.3scale.net
spec:
  validation:
    openAPIV3Schema:
      properties:
        spec:
          anyOf:
           - required: ["adminPortalCredentialsRef"]
           - required: ["embeddedConfigurationSecretRef"]
