# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/apps.3scale.net_apicasts.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_apicasts.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_apicasts.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch
#
# [APIcast CRD Configuration Source OpenAPI Validation]. This patch adds `anyOf` OpenAPI
# validation for the configuration source of APIcas to the APIcast CRD due to at the
# moment of writing this (2020-06-22) kubebuilder does not support `anyOf` statement
# OpenAPI validation
- patches/configuration_source_openapi_validation_in_apicasts.yaml
# +kubebuilder:scaffold:crdkustomizeapicastconfigurationsourceopenapivalidationpatch

# [APIcast CRD additional app label]. This patch adds the 'app' label for the APCIcast CRD
- patches/additional_app_label_in_crd.yaml
# +kubebuilder:scaffold:crdkustomizeadditionalapplabelincrdpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
